version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/setup-uv"
    schedule:
      interval: "weekly"
    labels: ["dependencies"]
    groups:
      codeql-action:
        patterns:
          - "github/codeql-action"
          - "github/codeql-action/*"
